site_name: My Docs
nav:
  - Home:
      - index.md
  - Scripting:
      - api:
          - lua/api/events.md
          - lua/api/conditions.md
theme:
  name: material
  color_mode: dark
  user_color_mode_toggle: true
#extra_css:
#  - css/rtd_dark.css
plugins:
  search: {}
markdown_extensions:
  toc:
      permalink: "#"
  smarty: {}
  sane_lists: {}
