site_name: Total War Rome 2 Docs
repo_url: https://github.com/bukowa/twr2docs
repo_name: Total War Rome 2 Docs
nav:
  - Home:
      - index.md
  - Scripting:
      - api:
          - lua/api/events.md
          - lua/api/conditions.md
theme:
  name: material
  color_mode: dark
  user_color_mode_toggle: true
#extra_css:
#  - css/rtd_dark.css
plugins:
  search: {}
markdown_extensions:
  toc:
      permalink: "#"
  smarty: {}
  sane_lists: {}
  pymdownx.critic: {}
  pymdownx.caret: {}
  pymdownx.keys: {}
  pymdownx.mark: {}
  pymdownx.tilde: {}
